#  StopAndCheck 1.2-BETA
#  https://github.com/justyXOR/StopAndCheck

#  Placeholders:
#    {player} - Replaced by the specified player in the command
#    {executor} - Replaced by the player who executed the command

check:
  teleport:
    enabled: false
    world: "world"
    coordinates: "-106 107 -12 0 0"   # Format: "X Y Z Yaw Pitch". Yaw and Pitch is optional
  on-disconnect:
    enabled: true
    command: "tempban {player} 60d Left from check"

messages:
  check-chat-tag: "&7[&bCheck&7] &f"
  you-tag: "&7[&9You&7]&r"
  cfg-reload: "&7[&6&lStopAndCheck&7] &fConfig reloaded"
  usage: "&cCorrectly like this:&f"
  moderator:
    no-permission: "&7[&6&lStopAndCheck&7] &fYou don't have permission"
    self-check: "&7[&6&lStopAndCheck&7] &fYou cannot call yourself to checking"
    self-free: "&7[&6&lStopAndCheck&7] &fDon't even try to get yourself released from the checking! >:("
    is-checking: "&7[&6&lStopAndCheck&7] &f{player} is checking another player"
    successful-called: "&7[&6&lStopAndCheck&7] &f{player} was called in to checking"
    successful-free: "&7[&6&lStopAndCheck&7] &fYou released {player} from check"
    player-offline: "&7[&6&lStopAndCheck&7] &fPlayer is offline"
    player-has-perm: "&7[&6&lStopAndCheck&7] &f{player} is immune to checks"
    already-check: "&7[&6&lStopAndCheck&7] &f{player} already on check"
    already-free: "&7[&6&lStopAndCheck&7] &f{player} not on a check"
    status-oncheck: "&c&lOn check"
    status-checking: "&b&lChecking another player"
    status-free: "&a&lFree"
    no: "&7No"
    info:
      - ""
      - "&6&lInformation about &7{player}"
      - ""
      - "&7Status: {info_status}"   #THESE PLACEHOLDERS WORK ONLY HERE
      - "&7Checking player: &6{checking_player}"
      - "&7Checking moderator: &6{checking_moderator}"
      - ""
  player:
    check-title: "&c&lCHEAT CHECKING"
    check-subtitle: "See chat for instructions"
    free-msg: "&7[&6&lStopAndCheck&7] &aYou were released from the check."
    check-chatmsg:
      - ""
      - "&c&lYou are suspected of cheating"
      - "&7By {executor}"
      - ""
      - "&71. &fWrite your discord to chat"
      - "&72. &fLeaving the server = ban for 60 days"
      - "&73. &fYou can talk with moderator in the chat"
      - "&74. &fYou cannot move, write commands, or throw objects"
      - ""
    help:
      - "&a/sac check <player> - Call player to check"
      - "&a/sac free <player> - Release player from check"
      - "&a/sac reload - Reload the config"
      - "&a/sac help - This menu"
      - "&a/sac info <player> - Information about player"